apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: update-repositorymirror
spec:
  description: Verify updating a RepositoryMirror CR reconciles the changes
  steps:
    - name: create-initial
      try:
        - apply:
            resource:
              apiVersion: quay.ayoy.se/v1alpha1
              kind: RepositoryMirror
              metadata:
                name: test-update
              spec:
                connSecretRef:
                  name: quay-credentials
                  namespace: quay-system
                name: testorg/testrepo
                externalReference: kind-registry:5000/ayoy/quay-config-operator
                robotUsername: testorg+robot
                syncInterval: "86400"
                imageTags:
                  - "latest"
    - name: assert-initial-created
      try:
        - assert:
            resource:
              apiVersion: quay.ayoy.se/v1alpha1
              kind: RepositoryMirror
              metadata:
                name: test-update
              status:
                existInQuay: true
                conditions:
                  - type: Running
                    status: "False"
                  - type: Successful
                    status: "True"
    - name: update-mirror
      try:
        - apply:
            resource:
              apiVersion: quay.ayoy.se/v1alpha1
              kind: RepositoryMirror
              metadata:
                name: test-update
              spec:
                connSecretRef:
                  name: quay-credentials
                  namespace: quay-system
                name: testorg/testrepo
                externalReference: kind-registry:5000/ayoy/quay-config-operator
                robotUsername: testorg+robot
                syncInterval: "172800"
                imageTags:
                  - "latest"
    - name: assert-updated
      try:
        - assert:
            resource:
              apiVersion: quay.ayoy.se/v1alpha1
              kind: RepositoryMirror
              metadata:
                name: test-update
              status:
                existInQuay: true
                conditions:
                  - type: Running
                    status: "False"
                  - type: Successful
                    status: "True"
