apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: delete-repositorymirror
spec:
  description: Verify deleting a RepositoryMirror CR cleans up properly
  steps:
    - name: create-credentials-secret
      try:
        - apply:
            resource:
              apiVersion: v1
              kind: Secret
              metadata:
                name: quay-credentials
              stringData:
                host: "http://quay-mock.quay-system.svc.cluster.local"
                token: "e2e-test-token"
                validateCerts: "false"
    - name: create-repositorymirror
      try:
        - apply:
            resource:
              apiVersion: quay.ayoy.se/v1alpha1
              kind: RepositoryMirror
              metadata:
                name: test-delete
              spec:
                connSecretRef:
                  name: quay-credentials
                name: testorg/testrepo
                externalReference: kind-registry:5000/ayoy/quay-config-operator
                robotUsername: testorg+robot
    - name: assert-exists
      try:
        - assert:
            resource:
              apiVersion: quay.ayoy.se/v1alpha1
              kind: RepositoryMirror
              metadata:
                name: test-delete
              status:
                existInQuay: true
    - name: delete-repositorymirror
      try:
        - delete:
            ref:
              apiVersion: quay.ayoy.se/v1alpha1
              kind: RepositoryMirror
              name: test-delete
    - name: assert-deleted
      try:
        - error:
            resource:
              apiVersion: quay.ayoy.se/v1alpha1
              kind: RepositoryMirror
              metadata:
                name: test-delete
