//go:build !ignore_autogenerated

/*
Copyright 2024 ayoy.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnSecretRef) DeepCopyInto(out *ConnSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnSecretRef.
func (in *ConnSecretRef) DeepCopy() *ConnSecretRef {
	if in == nil {
		return nil
	}
	out := new(ConnSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMirror) DeepCopyInto(out *RepositoryMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMirror.
func (in *RepositoryMirror) DeepCopy() *RepositoryMirror {
	if in == nil {
		return nil
	}
	out := new(RepositoryMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMirrorList) DeepCopyInto(out *RepositoryMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositoryMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMirrorList.
func (in *RepositoryMirrorList) DeepCopy() *RepositoryMirrorList {
	if in == nil {
		return nil
	}
	out := new(RepositoryMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMirrorSpec) DeepCopyInto(out *RepositoryMirrorSpec) {
	*out = *in
	out.ConnSecretRef = in.ConnSecretRef
	if in.IsEnabled != nil {
		in, out := &in.IsEnabled, &out.IsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ImageTags != nil {
		in, out := &in.ImageTags, &out.ImageTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VerifyTls != nil {
		in, out := &in.VerifyTls, &out.VerifyTls
		*out = new(bool)
		**out = **in
	}
	if in.UnsignedImages != nil {
		in, out := &in.UnsignedImages, &out.UnsignedImages
		*out = new(bool)
		**out = **in
	}
	if in.ForceSync != nil {
		in, out := &in.ForceSync, &out.ForceSync
		*out = new(bool)
		**out = **in
	}
	if in.PreserveInQuayOnDeletion != nil {
		in, out := &in.PreserveInQuayOnDeletion, &out.PreserveInQuayOnDeletion
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMirrorSpec.
func (in *RepositoryMirrorSpec) DeepCopy() *RepositoryMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMirrorStatus) DeepCopyInto(out *RepositoryMirrorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMirrorStatus.
func (in *RepositoryMirrorStatus) DeepCopy() *RepositoryMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryMirrorStatus)
	in.DeepCopyInto(out)
	return out
}
